echoesofcinema/urls.py
from django.contrib import admin
from django.urls import path, include, re_path
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('movie.urls')),
    path('users/', include('users.urls', namespace='users')),
    path('api/v1/', include('movie.api.urls')),
]


if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

movie/urls.py
from django.urls import path, register_converter
from movie import views
from movie.views import *


urlpatterns = [
    path('', views.MovieHome.as_view(), name='home'),
    path('about/', views.about, name='about'),
    path('contact/', views.contact, name='contact'),
    path('post/<slug:slug>/', views.Show_post.as_view(), name='post'),
    path('add_movie/', views.AddMovieView.as_view(), name='add_movie'),
    path('success/', views.success, name='success'),
]

users/urls.py
from django.contrib.auth.views import LogoutView, PasswordChangeDoneView, PasswordResetView, \
    PasswordResetDoneView, PasswordResetConfirmView, PasswordResetCompleteView
from django.urls import path
from . import views
from django.urls import reverse_lazy

app_name = "users"

urlpatterns = [
    path('login/', views.LoginUser.as_view(), name='login'),
    path('logout/', LogoutView.as_view(), name='logout'),
    path('register/', views.RegisterUser.as_view(), name='register'),
    path('profile/', views.ProfileUser.as_view(), name='profile'),
    path('password-change/', views.UserPasswordChange.as_view(), name='password_change'), # для обработки формы изменения пароля
    path('password-change/done/', PasswordChangeDoneView.as_view(template_name="users/password_change_done.html"), name="password_change_done"), # для отображения результата успешного изменения пароля
    path('password-reset/', PasswordResetView.as_view(template_name="users/password_reset_form.html", email_template_name="users/password_reset_email.html", success_url=reverse_lazy("users:password_reset_done")), name='password_reset'),
    path('password-reset/done/', PasswordResetDoneView.as_view(template_name="users/password_reset_done.html"), name='password_reset_done'),
    path('password-reset/<uidb64>/<token>/', PasswordResetConfirmView.as_view(template_name="users/password_reset_confirm.html", success_url=reverse_lazy("users:password_reset_complete")), name='password_reset_confirm'),
    path('password-reset/complete/', PasswordResetCompleteView.as_view(template_name="users/password_reset_complete.html"), name='password_reset_complete'),
]

templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="ru">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Echoes of Cinema</title>
    <link rel="stylesheet" href="{% static 'movie/css/main.css' %}">
</head>
<body>
    <!-- Меню -->
    <nav class="navbar">
        <div class="container">
            <a class="logo" href="{% url 'home' %}">Echoes of Cinema</a>
            <ul class="nav-menu-center">
                <li><a href="{% url 'add_movie' %}">Добавить фильм/сериал</a></li>
                <li><a href="{% url 'about' %}">О сайте</a></li>
                <li><a href="{% url 'contact' %}">Контакты</a></li>
            </ul>
            <ul class="nav-menu-right">
                {% if user.is_authenticated %}
                    <li><a href="{% url 'users:profile' %}">Профиль</a></li>
                    <li>
                        <form action="{% url 'users:logout' %}" method="post" style="display: inline;">
                            {% csrf_token %}
                            <button type="submit" class="btn-logout">Выйти</button>
                        </form>
                    </li>
                {% else %}
                    <li><a href="{% url 'users:login' %}">Войти</a></li>
                    <li><a href="{% url 'users:register' %}">Регистрация</a></li>
                {% endif %}
            </ul>
            <button class="menu-toggle">☰</button>
        </div>
    </nav>

    <!-- Основной контент -->
    <div class="container">
        {% block content %}
        {% endblock %}
    </div>

    {% block navigation %}
        {% if page_obj.has_other_pages %}
        <nav class="list-pages">
            <ul>
                {% if page_obj.has_previous %}
                <li class="page-num">
                    <a href="?page={{ page_obj.previous_page_number }}">&lt;</a>
                </li>
                {% endif %}

                {% for p in paginator.page_range %}
                {% if page_obj.number == p %}
                <li class="page-num page-num-selected">{{ p }}</li>
                {% elif p >= page_obj.number|add:-2 and p <= page_obj.number|add:2 %}
                <li class="page-num">
                    <a href="?page={{ p }}">{{ p }}</a>
                </li>
                {% endif %}
                {% endfor %}

                {% if page_obj.has_next %}
                <li class="page-num">
                    <a href="?page={{ page_obj.next_page_number }}">&gt;</a>
                </li>
                {% endif %}

            </ul>
        </nav>
        {% endif %}
    {% endblock %}

    <script src="{% static 'movie/js/main.js' %}"></script>
</body>
</html>